In [91]:
! /usr/local/bin/python3.12 -m pip install tensorflow keras

Requirement already satisfied: tensorflow in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.19.0)
Requirement already satisfied: keras in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.9.0)
Requirement already satisfied: absl-py>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (75.8.0)
Requirement already satisfied: six>=1.12.0 in /Users/dragonnomada/Library/Python/3.12/lib/python/site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (1.71.0)
Requirement already satisfied: tensorboard~=2.19.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (2.19.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (2.1.1)
Requirement already satisfied: h5py>=3.11.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (3.13.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorflow) (0.5.1)
Requirement already satisfied: rich in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from keras) (0.0.8)
Requirement already satisfied: optree in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from keras) (0.14.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2025.4.26)
Requirement already satisfied: markdown>=2.6.8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorboard~=2.19.0->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from rich->keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/dragonnomada/Library/Python/3.12/lib/python/site-packages (from rich->keras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)

[notice] A new release of pip is available: 25.0 -> 26.2.1
[notice] To update, run: python3.12 -m pip install --upgrade pip

In [92]:
import numpy
import pandas

from matplotlib import pyplot
import seaborn

# Redes neuronales
import keras

In [93]:
titanic3 = pandas.read_csv("../conjuntos/titanic3.csv")

titanic3

        Sex   Age Pclass2  Family Family2     Fare2 Cabin2 Embarked2 Survived2
0      male  22.0     3ra       1  couple  2.110213     no         S        no
1    female  38.0     1ra       1  couple  4.280593    yes         C       yes
2    female  26.0     3ra       0  single  2.188856     no         S       yes
3    female  35.0     1ra       1  couple  3.990834    yes         S       yes
4      male  35.0     3ra       0  single  2.202765     no         S        no
..      ...   ...     ...     ...     ...       ...    ...       ...       ...
886    male  27.0     2da       0  single  2.639057     no         S        no
887  female  19.0     1ra       0  single  3.433987    yes         S       yes
888  female   NaN     3ra       3  family  3.196630     no         S        no
889    male  26.0     1ra       0  single  3.433987    yes         C       yes
890    male  32.0     3ra       0  single  2.169054     no         Q        no

[891 rows x 9 columns]

In [95]:
pandas.__version__

'2.2.2'

In [101]:
pandas.get_dummies(titanic3[["Pclass2"]])[["Pclass2_1ra", "Pclass2_2da"]].astype(int)

     Pclass2_1ra  Pclass2_2da
0              0            0
1              1            0
2              0            0
3              1            0
4              0            0
..           ...          ...
886            0            1
887            1            0
888            0            0
889            1            0
890            0            0

[891 rows x 2 columns]

In [ ]:
x1 = (titanic3["Sex"] == "female").astype(int)
x1.name = "Sex_female"
x2 = titanic3["Age"]
x3 = (titanic3["Pclass2"] == "1ra").astype(int)
x3.name = "Pclass2_1ra"
x4 = (titanic3["Pclass2"] == "2da").astype(int)
x3.name = "Pclass2_2da"
x5 = titanic3["Family"]
x6 = (titanic3["Family2"] == "couple").astype(int)
x6.name = "Family2_couple"
x7 = (titanic3["Family2"] == "family").astype(int)
x7.name = "Family2_family"
x8 = titanic3["Fare2"]
x9 = (titanic3["Cabin2"] == "yes").astype(int)
x10 = (titanic3["Embarked2"] == "C").astype(int)
x10.name = "Embarked2_C"
x11 = (titanic3["Embarked2"] == "Q").astype(int)
x11.name = "Embarked2_Q"
x12 = (titanic3["Embarked2"] == "X").astype(int)
x12.name = "Embarked2_X"

y1 = (titanic3["Survived2"] == "yes").astype(int)

indices_edades_nulas = x2[x2.isna()].index # Índices de las edades conocidas
indices_edades_no_nulas = x2.dropna().index # Índices de las edades no conocidas
Cy = x2.dropna() # Edades conocidas
Cx = pandas.DataFrame([x1, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, y1]).T.loc[indices_edades_no_nulas] # Clúster de edades conocidas
Cp = pandas.DataFrame([x1, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, y1]).T.loc[indices_edades_nulas] # Clúster de predicción (para las edades no conocidas)

from sklearn.cluster import KMeans # MeanShift, AffinityPropagation

clu = KMeans(n_clusters=20) # Reconocer 20 tipos de clúster
clu.fit(Cx, Cy) # Entrenar el clúster
clusters = clu.predict(Cx) # Predecir el clúster para las edades conocidas
age_cluster = pandas.DataFrame({
    "Age": Cy.values, # Edades conocidas
    "Clu": clusters, # Clúster de las edades conocidas
}).groupby(["Clu"]).median() # Agrupadas y se extrae la mediana (para las edades conocidas)

X = pandas.DataFrame([x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12]).T # Las predictivas (sin imputar)
Y = pandas.DataFrame([y1]).T # Las respuestas

X.loc[x2.isna(), "Age"] = age_cluster.loc[clu.predict(Cp)]["Age"].values # Imputación de edades faltas por su edad mediana del clúster

X

,Sex,Age,Pclass2,Pclass2,Family,Family2,Family2,Fare2,Cabin2,Embarked2,Embarked2,Embarked2
0,0.0,22.0,0.0,0.0,1.0,1.0,0.0,2.110213,0.0,0.0,0.0,0.0
1,1.0,38.0,1.0,0.0,1.0,1.0,0.0,4.280593,1.0,1.0,0.0,0.0
2,1.0,26.0,0.0,0.0,0.0,0.0,0.0,2.188856,0.0,0.0,0.0,0.0
3,1.0,35.0,1.0,0.0,1.0,1.0,0.0,3.990834,1.0,0.0,0.0,0.0
4,0.0,35.0,0.0,0.0,0.0,0.0,0.0,2.202765,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.0,27.0,0.0,1.0,0.0,0.0,0.0,2.639057,0.0,0.0,0.0,0.0
887,1.0,19.0,1.0,0.0,0.0,0.0,0.0,3.433987,1.0,0.0,0.0,0.0
888,1.0,23.5,0.0,0.0,3.0,0.0,1.0,3.196630,0.0,0.0,0.0,0.0
889,0.0,26.0,1.0,0.0,0.0,0.0,0.0,3.433987,1.0,1.0,0.0,0.0
890,0.0,32.0,0.0,0.0,0.0,0.0,0.0,2.169054,0.0,0.0,1.0,0.0